jenkins:
  systemMessage: "ATS CI/CD Infrastructure - Multi-Platform Firmware Build System"

unclassified:
  location:
    adminAddress: "admin@ats-ci.local"
    url: "http://localhost:8080/"

tool:
  git:
    installations:
      - name: "Default"
        home: "git"

# Seed job to create folders and jobs using Job DSL
# This job will read the Job DSL script and create all folders/jobs
jobs:
  - script: |
      // Create folders structure
      folder('platforms') {
        displayName('Platforms')
        description('Platform-specific build and test pipelines')
      }
      
      folder('platforms/ESP32') {
        displayName('ESP32')
        description('ESP32 firmware build and test pipelines')
      }
      
      folder('platforms/RaspberryPi') {
        displayName('Raspberry Pi')
        description('Raspberry Pi image build and test pipelines')
      }
      
      folder('platforms/nRF52') {
        displayName('nRF52')
        description('nRF52 firmware build and test pipelines')
      }
      
      folder('ats-node') {
        displayName('ATS Node')
        description('ATS node container image build (runs on commit to ats-ats-node)')
      }
      
      // ATS Node Test Image — build & push on commit to ats-ats-node
      pipelineJob('ats-node/ats-node-test-image') {
        displayName('ATS Node Test Image')
        description('Build and push ats-node-test Docker image to GHCR. Triggered by commits to ats-ats-node.')
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/PicoPiece/ats-ats-node.git')
                  credentials('')
                }
                branches('*/main')
                scriptPath('Jenkinsfile')
              }
            }
          }
        }
        triggers {
          scm('H/5 * * * *')
        }
        parameters {
          stringParam('IMAGE', 'ghcr.io/picopiece/ats-node-test:latest', 'Full image name (registry/owner/name:tag)')
          stringParam('GHCR_CREDENTIALS_ID', '', 'Jenkins credentials ID for GHCR (required for push). Leave empty to skip push.')
        }
      }
      
      // ESP32 Build Job
      pipelineJob('platforms/ESP32/ats-fw-esp32-demo') {
        displayName('ESP32 Firmware Build')
        description('Build ESP32 firmware from source')
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/PicoPiece/ats-fw-esp32-demo.git')
                  credentials('')
                }
                branches('*/main')
                scriptPath('platforms/ESP32/Jenkinsfile')
              }
            }
          }
        }
        parameters {
          stringParam('BRANCH_NAME', 'main', 'Git branch to build (e.g., main, develop, feature/xxx)')
          booleanParam('TRIGGER_TEST', true, 'Trigger test pipeline after build completes')
          stringParam('TAG_PREFIX', 'esp32-fw', 'Prefix for firmware tag (e.g., esp32-fw, v, release)')
        }
      }
      
      // ESP32 Test Job
      pipelineJob('platforms/ESP32/ats-fw-esp32-demo-ESP32-test') {
        displayName('ESP32 Firmware Test')
        description('Test ESP32 firmware on ATS node')
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/PicoPiece/ats-fw-esp32-demo.git')
                  credentials('')
                }
                branches('*/main')
                scriptPath('platforms/ESP32/Jenkinsfile.test')
              }
            }
          }
        }
        parameters {
          stringParam('BUILD_JOB_NAME', 'platforms/ESP32/ats-fw-esp32-demo', 'Name of the build job that produced the firmware (with folder path)')
          stringParam('BUILD_NUMBER', '', 'Build number of the firmware to test')
          stringParam('ATS_NODE_LABEL', 'raspi-ats-01', 'Label for ATS node pool (e.g., raspi-ats-01, ats-node)')
          choiceParam('IMAGE_SOURCE', ['registry', 'build'], 'How to get ats-node-test image: pull from registry or build on agent')
          stringParam('ATS_NODE_TEST_IMAGE', 'ghcr.io/picopiece/ats-node-test:latest', 'Docker image name for ATS node test container (must be lowercase for registry)')
          stringParam('GHCR_CREDENTIALS_ID', '', 'Jenkins credentials ID for GHCR (leave empty if image is public)')
          stringParam('TEST_REPO_URL', 'https://github.com/PicoPiece/ats-test-esp32-demo.git', 'Git URL of the test framework repository')
          stringParam('TEST_REPO_BRANCH', 'main', 'Branch of the test framework repository to use')
        }
      }
